Racing Bands Visualizer
campmindshark/spectrum pull request #13
Opened 2019-08-16 20:31 UTC by speedplane

Here's a new visualizer. The idea behind it is that the dome is broken up vertically into several "racing" bands. Each band is controlled by volume, beat, is still, or rotates at a constant rate. Currently, the bands are hard-coded in there in the `RacerConfig` array, but if this seems to be popular, I'd be happy to adding some config options from within the VJ setup.

It's probably not as cool as I imagined in my head, but will be a nice variation to throw in. I'm curious as to whether it will make people motion sick with all the spinning swirly things around them.

Here's a screenshot of it in action in its default setup:

![image](https://user-images.githubusercontent.com/671052/63196241-d24ac200-c042-11e9-92e7-ee8662c29ec4.png)

2019-08-19 04:02 UTC, Ashoat requested changes
Awesome that you got a PR out, but there's a lot that needs to be cleaned up here.

There are some style nits inline. For each of them, please look through the PR for other instances of the same style issue. I didn't have time to go through each instance but I think there are more than one for each nit.

I didn't get a chance to go through your new `Visualizer` completely. I reviewed the other changes more deeply since they affect files other folks will touch. On the next review I'll try to go through your new `Visualizer` more thoroughly.

2019-08-19 04:02 UTC, Ashoat commented on Spectrum/Visualizers/LEDDomeRaceVisualizer.cs
> +namespace Spectrum
I am not sure how you got Visual Studio to ignore the `.editorconfig`. Are you not editing from within Visual Studio? The curly braces should be on the same line

2019-08-19 04:02 UTC, Ashoat commented on Spectrum/Visualizers/LEDDomeRaceVisualizer.cs
> +      double progressThroughHalfMeasure =
Please get rid of all of these unused variables that you copy-pasted from the example PR

2019-08-19 04:02 UTC, Ashoat commented on LEDs/LEDDomeOutput.cs
> +    public int GetSingleColor(int index, double intensity = 1.0) {
As far as I understand, your goal with this "intensity" parameter is simply to scale a color down. That is what `LEDColor.ScaleColor` is for. There's no reason for `GetSingleColor` to have to be concerned with your new intensity parameter.

Instead of adding this extra complexity to `GetSingleColor`, just have your caller call `LEDColor.ScaleColor` on the result of `GetSingleColor` instead.

2019-08-19 04:02 UTC, Ashoat commented on LEDs/LEDDomeOutput.cs
> +      if(pixelPos < 0 || pixelPos > 1) {
Space after `if` please

2019-08-19 04:02 UTC, Ashoat commented on LEDs/LEDDomeOutput.cs
> +    public int GetGradientBetweenColors(
I am not sure why this needs to exist, can you give some more context? Why do you need to interpolate a gradient between two distinct indices? The idea of a single index is that it already represents a gradient pair

2019-08-19 04:02 UTC, Ashoat commented on LEDs/LEDDomeOutput.cs
> +      int min_index,
Please use `camelCase` consistently

2019-08-19 04:02 UTC, Ashoat commented on README.md
> +## Dome Simulator
You put these changes in another PR. Please remove them from this one

2019-08-19 04:02 UTC, Ashoat commented on README.md
> +## Troubleshooting
Remove this please

2019-08-19 04:02 UTC, Ashoat commented on LEDs/LEDDomeOutput.cs
> +    public int GetGradientBetweenColors(
Line break between method definitions

2019-08-19 12:18 UTC, speedplane commented on LEDs/LEDDomeOutput.cs
> +    public int GetGradientBetweenColors(
Currently, a gradient handles just two colors. I wanted to make it easier to handle create gradients between more than two colors. The idea here is that we interpolate between all colors between `minIndex` and `maxIndex` evenly.

2019-08-19 12:19 UTC, speedplane commented
Fixed all the nits, happy to discuss `GetGradientBetweenColors` more, it's possible there's a better way to handle it.

2019-08-21 15:35 UTC, Ashoat approved these changes
Thanks for getting everything fixed up

2019-08-21 15:37 UTC, merged

2019-08-21 15:41 UTC, speedplane commented
Nice, thank you!